### ISSUE TITLE
IndexError after adding file to Windows 10 Installer iso, due to eltorito

### ISSUE THREAD

**Issue by gergelykalman** [clalancette/pycdlib#46] opened 2020-04-18 12:41 UTC
I'm back :)

So I installed pycdlib from master:

```
$ pip install git+https://github.com/clalancette/pycdlib.git
Collecting git+https://github.com/clalancette/pycdlib.git
  Cloning https://github.com/clalancette/pycdlib.git to /tmp/pip-req-build-fyslph7_
Installing collected packages: pycdlib
  Running setup.py install for pycdlib ... done
Successfully installed pycdlib-1.10.0
```

I tried adding a file through the udf facade and it fails with an exception.

code to reproduce:
```
import sys

import pycdlib


iso_in = sys.argv[1]
iso_out = sys.argv[2]
test_file = sys.argv[3]

iso = pycdlib.PyCdlib()
iso.open(iso_in)

udf = iso.get_udf_facade()

udf.add_file(test_file, "/testfile.txt")

# print(iso.eltorito_boot_catalog, dir(iso.eltorito_boot_catalog), iso.eltorito_boot_catalog.dirrecords)

# this works around the error, but prevents the image from booting
# iso.rm_eltorito()

iso.write(iso_out, progress_cb=lambda x, y, z: print(x/1024/1024, y/1024/1024, z))

iso.close()
```

The exception:
```
Traceback (most recent call last):
  File "pycdlib_bug.py", line 22, in <module>
    iso.write(iso_out, progress_cb=lambda x, y, z: print(x/1024/1024, y/1024/1024, z))
  File "/home/synapse/.virtualenvs/wuig/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 4318, in write
    self._write_fp(fp, blocksize, progress_cb, progress_opaque)
  File "/home/synapse/.virtualenvs/wuig/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 2827, in _write_fp
    self._reshuffle_extents()
  File "/home/synapse/.virtualenvs/wuig/lib/python3.7/site-packages/pycdlib/pycdlib.py", line 1596, in _reshuffle_extents
    current_extent += utils.ceiling_div(self.eltorito_boot_catalog.dirrecords[0].get_data_length(),
IndexError: list index out of range
```

ISO sha1: 344ca92459c23663d5f857c72a7c030f85f19be8

I tried to figure it out but this seems to be way out of my league.

If I use rm_eltorito() to remove the eltorito boot record this is fine, but obviously the cd won't boot.

**Comment by clalancette** [comment] 2020-04-19 15:17
Hm, yikes.  It looks like the boot catalog didn't get associated with a directory record, and there is some assumptions in there that all boot catalogs have a file.  I'll see if I can find a Windows ISO to reproduce.  Thanks for the report.

**Comment by gergelykalman** [comment] 2020-04-19 15:40
There is something up with that image, I just tried with the latest from microsoft and it worked just fine.

Win10_1909_EnglishInternational_x64.iso
31549049b73cef72456af0bff71f494e76e1f506
from: https://www.microsoft.com/en-us/software-download/windows10ISO

Thanks for looking into this

**Comment by gergelykalman** [comment] 2020-04-19 15:42
Oh, of course let me know if you need the image in question, I'm happy to share it.

**Comment by clalancette** [comment] 2020-06-03 00:22
All right, I was finally able to find this image and find some time to debug the problem.

It looks like this ISO showed two separate problems in pycdlib:
1.  We weren't retaining *all* of the Boot Record system use field.  There were certain circumstances in which we would remove portions of it, which was a bug.
1.  If the El Torito boot catalog had absolutely no links at all to it, we couldn't properly move things around on the image.  This is the what you ran into here.

I've fixed both of these issues on master.  Please give it another try.  I'm going to close this out for now, but feel free to reopen if the fixes don't work for you.

Thanks for the report!

**Closed by clalancette** 2020-06-03 00:22 UTC

**Comment by computerquip-work** [comment] 2025-09-29 21:55
Just FYI, I was trying to build a bootable windows ISO with the help of this and it does not work with any Windows ISO that I can find. rm_eltorito or add_eltorito both fail. EDIT: For those who find this, I ended up having to use xorriso / mkisofs instead from the command-line.
