### ISSUE TITLE
Big Endian Handling Errors

### ISSUE THREAD

**Issue by clebergnu** [clalancette/pycdlib#39] opened 2019-11-14 13:15 UTC
On an s390x system, running RHEL 7.7 (from IBM LinuxOne free offerings):

```
============================================================== test session starts ===============================================================
platform linux -- Python 3.6.8, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
rootdir: /home/linux1/src/pycdlib
collected 227 items                                                                                                                              

test_dates.py .......................                                                                                                      [ 10%]
test_rockridge.py .............................................F.......................................................................... [ 62%]
...................................................                                                                                        [ 85%]
test_utils.py FF...............................                                                                                            [100%]

==================================================================== FAILURES ====================================================================
_____________________________________________________________ test_rrpxrecord_record _____________________________________________________________

    def test_rrpxrecord_record():
        px = pycdlib.rockridge.RRPXRecord()
        px.new(0)
        rec = px.record('1.09')
>       assert(rec == b'PX\x24\x01\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00')
E       AssertionError: assert b'PX$\x01\x00...0\x00\x00\x00' == b'PX$\x01\x00...0\x00\x00\x00'
E         At index 12 diff: b'\x00' != b'\x01'
E         Use -v to get the full diff

test_rockridge.py:301: AssertionError
________________________________________________________________ test_swab_32bit _________________________________________________________________

    def test_swab_32bit():
>       assert(pycdlib.utils.swab_32bit(0x89) == 0x89000000)
E       AssertionError: assert 137 == 2298478592
E        +  where 137 = <function swab_32bit at 0x3ffab958ea0>(137)
E        +    where <function swab_32bit at 0x3ffab958ea0> = <module 'pycdlib.utils' from '../.././pycdlib/utils.py'>.swab_32bit
E        +      where <module 'pycdlib.utils' from '../.././pycdlib/utils.py'> = pycdlib.utils

test_utils.py:25: AssertionError
________________________________________________________________ test_swab_16bit _________________________________________________________________

    def test_swab_16bit():
>       assert(pycdlib.utils.swab_16bit(0x55aa) == 0xaa55)
E       AssertionError: assert 21930 == 43605
E        +  where 21930 = <function swab_16bit at 0x3ffab958f28>(21930)
E        +    where <function swab_16bit at 0x3ffab958f28> = <module 'pycdlib.utils' from '../.././pycdlib/utils.py'>.swab_16bit
E        +      where <module 'pycdlib.utils' from '../.././pycdlib/utils.py'> = pycdlib.utils

test_utils.py:28: AssertionError
========================================================= 3 failed, 224 passed in 1.42s ==========================================================
```

Tested commit 95aca81febb82546fca30d5644a286254a4593e4.

**Comment by clalancette** [comment] 2019-11-15 16:03
Oh yeah, good point.  On big-endian, those will be no-ops.  The bigger question is whether the code that uses them does the right thing on big-endian; nobody has tried yet, so I'm not sure :).

**Comment by willianrampazzo** [comment] 2019-11-18 21:14
I'm investigating this issue and may have found the problem. I ran the failing test (`test_rockridge.py:test_rrpxrecord_record`) manually on x86 and on s390x:

```
import pycdlib
px = pycdlib.rockridge.RRPXRecord()
px.new(0)
rec = px.record('1.09')
```

To improve the visibility of the problem, I changed `group_id` to `1` at `rockridge.py`, line 494, as this is the last parameter on `struct.pack` call at line 513.

Here is the content of `rec` on s390x:
PX$\x01\x00\x00\x00\x00\x00\x00\x00\x00 **\x00\x00\x00\x01** \x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00 **\x00\x00\x00\x01** \x00\x00\x00\x01

And here is the content of `rec` on x86: 
PX$\x01\x00\x00\x00\x00\x00\x00\x00\x00 **\x01\x00\x00\x00** \x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00 **\x01\x00\x00\x00** \x00\x00\x00\x01

As can be seen, `posix_file_links` and `group_id` original parameters (that are not swabbed) are swapped. The problem happened just because `posix_file_links` is set to `1`. If it was `0`, just like the other parameters, we would not notice the problem.

As those ISO standards are new to me, I still do not know how to fix it (maybe swab everything?). So, for now, I'm going through the ISO and IEEE documents to learn more about these standards and try to propose a fix. Any help here is appreciated :)

**Comment by willianrampazzo** [comment] 2019-11-18 21:24
> Oh yeah, good point. On big-endian, those will be no-ops. The bigger question is whether the code that uses them does the right thing on big-endian; nobody has tried yet, so I'm not sure :).

So you are in luck today as they are working as designed. :D

Here is the output on s390x showing that the function do not swab the bits as those are already BE.:
```
>>> import pycdlib
>>> import struct
>>> struct.pack('=L', 1)
b'\x00\x00\x00\x01'
>>> struct.pack('=L', pycdlib.utils.swab_32bit(1))
b'\x00\x00\x00\x01'
```

And here is the output on x86 showing the function swab the bits as those are LE.:
```
>>> import pycdlib
>>> import struct
>>> struct.pack('=L', 1)
b'\x01\x00\x00\x00'
>>> struct.pack('=L', pycdlib.utils.swab_32bit(1))
b'\x00\x00\x00\x01'
```

**Comment by clalancette** [comment] 2019-11-19 15:05
Thanks for the feedback.

It turns out that my whole concept of how the swabbing works isn't really correct, though.  I've been working on a patch locally that *should* fix most of the problems on big-endian machines.  It's not quite done yet, but I'll post here again once I have something that I think will work.

**Comment by willianrampazzo** [comment] 2019-11-19 15:22
> It turns out that my whole concept of how the swabbing works isn't really correct, though. I've been working on a patch locally that _should_ fix most of the problems on big-endian machines. It's not quite done yet, but I'll post here again once I have something that I think will work.

Okay, in this case, I can offer my help to test whatever you need on the s390x side.

**Comment by clalancette** [comment] 2019-11-22 15:28
FYI, I did some work on the https://github.com/clalancette/pycdlib/tree/big-endian-fixes2 branch.  They work in my testing on little-endian, but not completely on big-endian MIPS that I'm emulating.  More work is needed (hopefully this weekend).

**Comment by willianrampazzo** [comment] 2019-11-22 15:45
> FYI, I did some work on the https://github.com/clalancette/pycdlib/tree/big-endian-fixes2 branch. They work in my testing on little-endian, but not completely on big-endian MIPS that I'm emulating. More work is needed (hopefully this weekend).

Thanks for your prompt answer to it. I did some testing on s390x and, indeed, it is still failing.

**Comment by clalancette** [comment] 2019-11-23 20:35
All right, I had some time today to look at this.  Commit a70023167ab06d66190b4bc00475cbf643ae58eb changes up the code to be a lot more deliberate about endianness.  In my testing, this seems to work both for my little-endian x86_64 laptop, and for my big-endian MIPS qemu machine.

I've also setup travis to run tests on both x86_64 and s390x, and the tests all pass there.  So I'm confident that this will fix the problems you have had (and they should remain fixed in the future).  That being said, I'd appreciate any additional testing you do.

I'm going to close this issue out.  Thanks for the report and the testing up to this point.

**Closed by clalancette** 2019-11-23 20:35 UTC

**Comment by willianrampazzo** [comment] 2019-11-25 20:37
Thanks for your quick action on this issue. I have tested the new code on our project, and it worked without problems.

**Comment by clebergnu** [comment] 2019-11-25 20:40
@clalancette are you expecting to release a new version anytime soon? It would be nice to have this fix on a release we can fetch from PyPI.  Thanks!

**Comment by clalancette** [comment] 2019-11-26 02:56
> Thanks for your quick action on this issue. I have tested the new code on our project, and it worked without problems.

Great, thanks for the test.

> @clalancette are you expecting to release a new version anytime soon? It would be nice to have this fix on a release we can fetch from PyPI. Thanks!

I'm in the middle of trying to get another bug/feature fixed for the next release (more robust UDF support).  I'll be working on that the next couple of weeks (with Thanksgiving in between).  If I don't get that done before mid-December, I'll cut a release without it.  Do feel free to open an issue to remind me if I don't get one out before that.

**Comment by clebergnu** [comment] 2019-12-18 16:27
Hi @clalancette, this is just a friendly reminder about a release with the fixes associated with this PR included.  Thanks, and happy Holidays!

**Comment by clalancette** [comment] 2019-12-20 15:35
Sorry for the delay.  I've now done a 1.9.0 release.  Thanks again!

**Comment by clebergnu** [comment] 2019-12-20 15:48
Great news! Thanks! FIY @willianrampazzo

**Comment by willianrampazzo** [comment] 2019-12-20 17:28
Awesome! Thanks @clalancette.
