### ISSUE TITLE
Search optimization doesn't work in find_file_ident_desc_by_name()

### ISSUE THREAD

**Issue by lightagain** [clalancette/pycdlib#18] opened 2019-01-14 13:05 UTC
I'm trying to create iso image with command:
`pycdlib-genisoimage -udf -o c:\image.iso c:\CD`
where contents of c:\CD is in [cd.zip](https://github.com/clalancette/pycdlib/files/2755153/cd.zip)
fails with 
```
File "c:\Program Files\Python36\lib\site-packages\pycdlib\udf.py", line 3204, in find_file_ident_desc_by_name
  raise pycdlibexception.PyCdlibInvalidInput('Could not find path')
```
If I disable search optimization in pycdlib/udf.py line 3174 (master branch) by replacing
`if self.icb_tag.flags & 0x8 or self.is_sorted:`
with
`if False and (self.icb_tag.flags & 0x8 or self.is_sorted):`
than iso created succesfully.

Apparently, search optimization doesn't work for encodings other than latin-1

**Comment by clalancette** [comment] 2019-01-14 19:50
Thanks for the report!  Unfortunately, the problem is worse than the fact that the search optimization doesn't work; it looks like I probably misinterpreted the UDF specification when I wrote the code to handle non-latin1 characters.  I'll need to go back and re-read the spec and see what the right thing to do here is.  This will take me a few days, but once this is fixed I'll make sure to add a test case for this.  Thanks again.

**Comment by clalancette** [comment] 2019-01-16 04:47
Commit 0ee74ffd6248b43fd07093441d45c34c277fbe37 fixes the issue (basically by removing the optimization as you originally pointed out), and commit 63891eb43567fa3c5610991aa74993e967056201 adds a test to ensure that it is fixed in the future.  Please give the latest master a try when you get a chance.  With that, I'm going to close this out, but feel free to keep commenting here.  Thanks again for the detailed report and reproducer; it allowed me to pinpoint the problem really quickly.

**Closed by clalancette** 2019-01-16 04:47 UTC
