### ISSUE TITLE
Windows OS compatability for loading directly from disc device?

### ISSUE THREAD

**Issue by rlaPHOENiX** [clalancette/pycdlib#50] opened 2020-06-18 05:14 UTC
pycdlib doesn't seem to work on Windows 10 64-bit, Python 3.7 64-bit.

I tried multiple things like:
```
from pycdlib import PyCdlib

cdlib = PyCdlib()
#cdlib.open("E:")  # fails, cant find the device
cdlib.open(r"\\.\E:")  # finds the device but fails on seeks.
```

**Comment by clalancette** [comment] 2020-06-18 13:00
I've honestly never tried.  I don't have a Windows machine handy, but I guess I can give it a shot with my Windows VM and see what happens.

**Comment by rlaPHOENiX** [comment] 2020-06-18 16:31
Yeah it seems to fail with the f.seek(), even if you manually load via `open(r"\\.\E:", "rb")` on an admin cmd/powershell, it still fails. For some reason only f.seek(0) works, literally no other value works.

**Comment by clalancette** [comment] 2020-06-19 00:02
All right, I see.  This program works in Windows:

```
import binascii
import sys

with open(r'\\.\D:', 'rb') as infp:
    infp.seek(2048)
    data = infp.read(512)
    print(binascii.hexlify(data))
```

In Windows, it turns out that you can only seek to the block size of the device when opening up the "raw" device.  For ISOs, the blocksize is basically always 2048.  Needless to say, pycdlib doesn't do that, and so runs afoul of this restriction.

Fixing this in pycdlib would be possible, but would honestly be quite a large undertaking.  Most of the code assumes it can seek randomly around.  In order to change it to blocksize-only seeks, we would have to revamp all of the reading code to read in blocksize chunks, then seek within those chunks.

I'm unlikely to do this anytime soon, but I'd be happy to review a patch if you'd be willing to work on it.

**Comment by rlaPHOENiX** [comment] 2020-06-19 14:58
I made work on a wrapper to open() that should deal with everything, except it isn't a true inheritor or anything, so it doesn't deal with disposing, but it works for random value seek and reads :+1: 

    import io
    import math


    class WindowsDeviceReader:

      def __init__(self, device, buffer_size=2048):
        self.__f = open(device, "rb")  # expecting device to be r"\\.\E:" e.t.c
        self.__int_sector_size = 512  # maybe get this from a win api just in case?
        self.__pos = 0  # position to remind .read() where we want to read from
        self.__pos_real = 0  # the real position the stream is at

      def read(self, size):
        """
        Reimplement custom read to be divisible by int_sector_size

        This is currently assuming that we want to read starting from
        the current position in the device stream, but that might not be the case.
        """
        if size % self.__int_sector_size == 0:
          # nice its divisible by int_sector_size, we can just read a sector
          print("Size was divisible")
          data = self._read(1)
        else:
          # not divisible by int_sector_size, let's calculate the minimum amount of reads
          print("Size NOT divisible")
          # required to obtain all bytes asked by the read request
          reads = size / self.__int_sector_size
          # read the amount of reads we need to make
          data = self._read(reads)
        # but we still need to handle the current spoof pos
        # remove the data the read didn't ask for
        offset = self.__pos - self.__pos_real
        end = offset + size
        print(f"Chopping the read data, keeping {offset}-{end}")
        data = data[offset:end]
        # return the data
        return data
      
      def _read(self, amount=1):
        """
        Read and return *int_sector_size* x *amount* of bytes
        Amount will automatically be rounded up to the nearest integer
        This is to make sure we are reading in a divisible amount of *int_sector_size*
        """
        amount = math.ceil(amount)
        print(f"_read :: Reading {self.__int_sector_size * amount} bytes")
        return self.__f.read(self.__int_sector_size * amount)
      
      def seek(self, to):
        """
        Reimplement custom seek to be divisible by int_sector_size
        """
        # Calculate the closest sector pos we can seek to while being divisible by
        # int_sector_size and still containing the data .read() wants
        sector_aligned_from = math.floor(to / self.__int_sector_size) * self.__int_sector_size
        if self.__f.seek(sector_aligned_from) != sector_aligned_from:
          raise Exception("Fill in this exception, idk how you like to do exceptions")
        # Return and spoof where we seeked to
        self.__pos = to
        self.__pos_real = sector_aligned_from
        return to


    f = WindowsDeviceReader(r"\\.\E:")

    # For a test, let's go to DVD sector 16 (1st actual data segment)
    # Let's just take the volume descriptor id (CD001), skipping
    # the volume descriptor type (for pvd, \x01)

    ## SEEKING

    seek = f.seek((2048 * 16) + 1)
    # this seek should actually seek to 2048 * 16 since thats to closest
    # starting sector that it can read from while having all the data we
    # actually want, it jotted down the seek pos we actually wanted though
    print(seek)  # this will be spoofed to return the value we asked to seek to

    ## READING

    # since the volume descriptor id (CD001) is 5 bytes long, lets grab 5 bytes
    # since we did ask to seek to (2048 * 16) + 1, it should start reading from
    # the correct position, even though internally it isn't actually at that
    # postition
    read = f.read(5)  # this should return b'CD001'
    print(read)
    print(f"{len(read)} bytes read")

    # logically validate test
    if seek != (2048 * 16) + 1:
      raise ValueError("Seek test failed")
    if read != b'CD001':
      raise ValueError("Read test failed")

**Comment by clalancette** [comment] 2020-10-09 02:19
I spent some time this evening making pycdlib work with raw Windows devices.  It was actually easier than I expected.  Along the way, I also discovered a few other bugs when working on Windows, which I also fixed.  When you get a chance, please test out the master branch of pycdlib, which has all of these fixes.

Thanks again for the report.  I'm going to close this out, but feel free to keep commenting or reopen if it still doesn't work for you.

**Closed by clalancette** 2020-10-09 02:19 UTC

**Comment by rlaPHOENiX** [comment] 2020-10-10 06:41
Hi, great stuff, glad Windows support is moving along.

Anyhow, 1.11.0 which is currently on pypi, isn't working. walk_dirs for some reason tries to seek to the end, which it cant. That's fine because you seem to have done changes since and fixed that, but haven't released v1.12.0 onto pypi.

Anyhow, if I manually install from master, it seems to work? I can't really tell to be honest. It's been in a frozen state for a good 3 minutes, and my code simply open()'s the device, then once open gets the primary volume descriptor information for the volume ID and that's it.

**Comment by rlaPHOENiX** [comment] 2020-10-10 06:47
If I'm reading the code for _get_iso_size correctly, it seems like it's actually going to end up reading the ENTIRE drive's content's before finding the end size, probably why its taking incredibly long :(

**Comment by clalancette** [comment] 2020-10-10 12:20
> Anyhow, 1.11.0 which is currently on pypi, isn't working. walk_dirs for some reason tries to seek to the end, which it cant. That's fine because you seem to have done changes since and fixed that, but haven't released v1.12.0 onto pypi.

Yeah, I just did the changes on master for now.  I'll eventually do another release, but I'm not quite ready yet.

> If I'm reading the code for _get_iso_size correctly, it seems like it's actually going to end up reading the ENTIRE drive's content's before finding the end size, probably why its taking incredibly long :(

It doesn't read the entire device, but it does seek through the whole thing 2048 bytes at a time.  It's the only thing I could find on Windows that would let me get the size on a raw device.

I suppose one thing we could do instead is to assume the size of the device and do some kind of binary search for the real size.  It would be faster than what is there, but it won't be fast.  I'm open to other ideas.

**Comment by rlaPHOENiX** [comment] 2020-10-10 22:26
Does it have to be 2048 bytes? On my test script that did a hacky workaround, I was doing it by 512 bytes.

Maybe it needs to simply be divisable by 512?

Is it also really necessary to find the seek_end at this stage of opening a disc? Maybe you can leave that off until doing an action that would require it?

**Comment by clalancette** [comment] 2020-10-12 00:29
> Is it also really necessary to find the seek_end at this stage of opening a disc? Maybe you can leave that off until doing an action that would require it?

Unfortunately, we have to do it right when opening the disc at the beginning.  We check that value every time we read a directory entry.

> Does it have to be 2048 bytes? On my test script that did a hacky workaround, I was doing it by 512 bytes.

No, it just has to be a 512-byte boundary as you point out.  But that would be even slower.

> 
> Maybe it needs to simply be divisable by 512?

Yeah, that idea is workable.  In commit cdce4ed0b1f9b28e3bad99dbcd3945eaf86797ff, I revamped it to read by 1MB chunks, then backup and find the closest 2048-byte boundary (since the ISO should be some multiple of 2048).  In my testing locally, this reduced the time on reading a 915MB ISO from 25 seconds to 2 seconds, so it should be a lot faster.

How big is the ISO you are trying to open?  It is obviously going to take longer with bigger ISOs.  In any case, please give the latest master code a test and let me know how it goes for you.

**Comment by rlaPHOENiX** [comment] 2020-10-12 10:36
From what I understand your testing this by opening a .ISO file on your HDD/SSD, and not from a DVD drive correct? That's probably why it takes so long for me, since you are in fact READING the ISO every seek, your not just seeking, your reading data into memory at the same time, less memory with the commit now but still. My test's are reading directly from a DVD drive, specifically a DVD9 (Single-Sided Dual-Layer), which is about 7.1 GiB.

If your curious by the way, I'm using your code on an open source project of mine, `pip install pslipstream` then run it with `pslipstream`, works on windows too, but must be installed and used on python 3.6.x or 3.7.x, nothing newer or older.

I might not be able to test this for another bit sadly, but hopefully that commit will improve things :)

**Comment by clalancette** [comment] 2020-10-13 01:27
> From what I understand your testing this by opening a .ISO file on your HDD/SSD, and not from a DVD drive correct? 

Sort of.  I have a Linux machine with a Windows VM.  I pass an ISO into the Windows VM as a raw device.  So from the Windows side it acts like a drive, but it is much faster than a real DVD drive.

> My test's are reading directly from a DVD drive, specifically a DVD9 (Single-Sided Dual-Layer), which is about 7.1 GiB.

Yeah, that's going to be a *lot* slower than what I am testing.  But I'll encourage you to still test it, and see how long it takes.  At the very least, having a baseline number gives us something to work on to optimize.

**Comment by rlaPHOENiX** [comment] 2021-04-10 12:21
Ok so update on all this. As I previously suggested, it is in fact reading one byte at a time, therefore the entire file.

The `self._cdfp.seek(one_mb_block * bs)` call results in it never actually seeking. As in, ever. Running a `tell()` after it results in `0` every time.

**Comment by clalancette** [comment] 2021-04-10 13:59
> The `self._cdfp.seek(one_mb_block * bs)` call results in it never actually seeking. As in, ever. Running a `tell()` after it results in `0` every time.

That's weird.

At the end of the day, if `seek`/`tell` don't work as we expect, then nothing in pycdlib is going to work.  It relies quite heavily on those methods to do all of the work.  That being said, I'd find it quite surprising if this was a fundamental limitation in Windows or Python; it would mean that *any* program trying to do these things would be quite hamstrung.

Unfortunately, I don't know how to help any further here.  I can't reproduce this problem on my Windows Virtual Machine, and I don't have hardware to reproduce.

That being said, if you come up with more ideas or solutions, please feel free to open another issue or pull request.  I'm happy to discuss further options.

**Comment by rlaPHOENiX** [comment] 2021-04-12 08:54
What I previously said may not actually be accurate, might have just been how I called the device.

Regardless, it is still painfully slow. Like, painfully. In this regard, I have found a potential solution though sadly it would result in another dependency, `wmi`.

`wmi` allows you to call Win32 APIs, and there's one that allows you to see tons of information about a CD ROM drive (which is also used for DVDs, Blu-rays, e.t.c).

```py
import wmi

DEVICE_SENT_TO_PYCDLIB_OPEN = 'D:'

pythoncom.CoInitialize()  # important if running in a background thread!
c = wmi.WMI()
drives = c.Win32_CDROMDrive()
for drive in drives:
    if drive.drive == DEVICE_SENT_TO_PYCDLIB_OPEN:
        size = int(drive.size)
        print(size)
>>>7404431360
```

An example of possible returned values on a real DVD Drive with a DVD inserted:
```
{
        Availability = 3;
        Capabilities = {3, 4, 7};
        CapabilityDescriptions = {"Random Access", " Supports writing", " Supports Removable Media"};
        Caption = "ASUS SDRW-08U7M-U USB Device";
        CompressionMethod = "Unknown";
        ConfigManagerErrorCode = 0;
        ConfigManagerUserConfig = FALSE;
        CreationClassName = "Win32_CDROMDrive";
        Description = "CD-ROM Drive";
        DeviceID = "USBSTOR\\CDROM&VEN_ASUS&PROD_SDRW-08U7M-U&REV_A101\\<<Serial Blanked>>_________&0";
        Drive = "D:";
        DriveIntegrity = TRUE;
        FileSystemFlagsEx = 21496327;
        Id = "D:";
        Manufacturer = "(Standard CD-ROM drives)";
        MaximumComponentLength = 254;
        MediaLoaded = TRUE;
        MediaType = "DVD Writer";
        MfrAssignedRevisionLevel = "A101";
        Name = "ASUS SDRW-08U7M-U USB Device";
        PNPDeviceID = "USBSTOR\\CDROM&VEN_ASUS&PROD_SDRW-08U7M-U&REV_A101\\<<Serial Blanked>>_________&0";
        SCSIBus = 0;
        SCSILogicalUnit = 0;
        SCSIPort = 0;
        SCSITargetId = 0;
        SerialNumber = "<<Serial Blanked>>         ";
        Size = "7404431360";
        Status = "OK";
        SystemCreationClassName = "Win32_ComputerSystem";
        SystemName = "DESKTOP-MJJSL3Q";
        TransferRate = 102.225535086785;
        VolumeName = "POKEMON";
        VolumeSerialNumber = "<<Serial Blanked>>";
};
```

Perhaps we could use this value as a drop-in, perhaps have `wmi` as an `extra`, and if installed then use it, otherwise just use what its doing right now.

**Comment by rlaPHOENiX** [comment] 2021-04-12 08:58
And hey, here's a shorter more convenient way to do that example call:
```py
from wmi import WMI

c = WMI()
pycdlib_device = "D:"
drive = next(iter(c.Win32_CDROMDrive(Drive=pycdlib_device)), None)
if drive:
    print(int(drive.size))
```

**Comment by rlaPHOENiX** [comment] 2021-04-12 11:51
```py

        try:
            from wmi import WMI
        except ImportError:
            pass
        else:
            c = WMI()
            win_device = ''.join(filter(str.isalpha, self._cdfp.name)) + ':'
            drive = next(iter(c.Win32_CDROMDrive(Drive=win_device)), None)
            if drive:
                return int(drive.size)
```

In _get_iso_size, after the SEEK_END + tell() check, put this. If any of it fails or the device is somehow not found, then no worries it tries what it currently does. Tested and working.

**Comment by rlaPHOENiX** [comment] 2021-04-14 19:39
After the above pull request with the following further changes to pycdlib.py:

![image](https://user-images.githubusercontent.com/17136956/114768849-4f22c780-9d61-11eb-8382-704778306f1b.png)

It works on a live disc!
Pretty much all of my discs have only one valid UDF Anchor since the 3rd one gets completely cut off by windows for some reason (see pull request comments). Only UDF Anchor 1 is valid, the 2nd one is just 2048 bytes of 0x1d. This is why I made changes to the UDF Anchor length check.
