### ISSUE TITLE
Corrupt file in UDF image

### ISSUE THREAD

**Issue by srowe** [clalancette/pycdlib#74] opened 2021-09-10 11:48 UTC
I've run into a problem when creating images with largish files, given the following code

```python
import os
import sys


import pycdlib


iso = pycdlib.PyCdlib()
iso.new(interchange_level=4, udf='2.60')

datafp=open(sys.argv[1], 'rb')
s = os.stat(sys.argv[1])
datalen=s.st_size

iso.add_fp(datafp, datalen, iso_path=None, udf_path='/test.bin')
iso.write(sys.argv[2])
iso.close()
```

I get a file of the correct size but the wrong contents if I give it a 2GB file

```shell
mnt_point=/test_mnt

dd if=/dev/urandom of=test.bin bs=1M count=2000
python3 write_udf.py test.bin test.iso

sudo mount -t udf -o ro test.iso $mnt_point

ls -l test.bin $mnt_point/test.bin
md5sum test.bin $mnt_point/test.bin
cmp test.bin $mnt_point/test.bin

sudo umount $mnt_point
```

The point at which the contents are wrong is rather strange

```
2000+0 records in
2000+0 records out
2097152000 bytes (2.1 GB) copied, 14.1198 s, 149 MB/s
-rw-r--r-- 1 simon.rowe Domain.Users 2097152000 Sep 10 11:41 test.bin
-r--r--r-- 1 nfsnobody  nfsnobody    2097152000 Sep  9 11:41 /test_mnt/test.bin
08e550aa8aba27e6e7dfd809ddc4906a  test.bin
988b6b2ffffc52699d384d7557996916  /test_mnt/test.bin
test.bin /test_mnt/test.bin differ: byte 1073739777, line 4192383
```

1073739777 is a byte past 0x3FFFF800

**Comment by srowe** [comment] 2021-09-10 11:51
I can see this value mentioned in `UDFExtendedFileEntry` but I can't see where that class is used.

**Comment by srowe** [comment] 2021-09-10 11:52
I can also create an image using `genisoimage` and the contents are correct.

**Comment by clalancette** [comment] 2021-09-12 20:52
Yeah, the large file support in UDF is definitely buggy.  This is essentially a duplicate of #65 , where the same problem was reported.  I've poked at it a bit, but I really haven't had time to dig into it in detail.  I'm going to close this as a duplicate, and hopefully I'll find time in the near future to really debug and fix this problem.

**Closed by clalancette** 2021-09-12 20:52 UTC
